# -*- coding: utf-8 -*-
"""Python Part - 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoiJ7ct91yOoXXMv8aOZjjirTGAHE75a

**Syntax Practice**

**Problem 1**

Print:

Hello Python
"""

print("Hello Python")

"""**Problem 2**

Print the following on separate lines:

Name: Anjali,
Course: M.Sc Data Science & AI
"""

name = "Anajli"
course = "M.Sc Data Science & AI"
print(name)
print(course)

"""**Problem 3**

Create variables for your name and age, then print them.
"""

name = "Anjali"
age = 24
print(f"I am {name} and am {age} year old ")

"""**Problem 4**

Create three variables:
Print them in one sentence.
"""

city = "Shimla"
state = "Himachal Pradesh"
country = "India"
print(f"I am from {country} and live in {city},{state}")

"""**Problem 5**
The following code contains an IndentationError. Fix it.
"""

"""
x = 5
if x > 0:
print("greater")
"""

x = 5
if x > 0:
  print("greater")

"""**Problem 6**

The following code contains a SyntaxError. Fix it.
"""

'''
name = "Anjali
age = 24
if age > 25
print (eligible)
'''

name = "Anjali"
age = 24
if age > 25:
  print("eligible")

"""**Problem 7**

Create two variables:

Assign different values and print both to show that Python is case-sensitive.
"""

name = "Anjali"
Name = "Amol"
print(name, Name)

"""**Problem 8**

Write an if statement with proper indentation.
"""

x = 80
if x > 50:
  print("pass")
else:
  print("fale")

"""**Problem 9**

Rewrite the following code according to Python style.
"""

'''
$ in this we are checking anjali name is there .
@myname = Anajli
if @myname = "Anajli":
     print("yes")
     if @myname = "Amol"
      print("no")
'''
# in this we are checking anjali name is there .
my_name = "Anjali"
if my_name == "Anjali":
  print("yes")
  if my_name == "Amol":
    print("no")

"""**Problem 10**

Write a program using:

one single-line comment
one inline comment
"""

# this is 10th proble of syntax
x = 23
print(x + 2) # we need 25

"""**Variables**

**Problem 11**

Create the following variables and print them.
"""

name = "Anjali"
price = 23.5
age = 23
Name =  ['Anajli','Amol','Abhishak']
print(name)
print(price)
print(age)
print(Name)
print(type(Name))

"""**Problem 12**

Swap the values of two variables without using a third variable.
"""

x = 5
y = 7
x, y = y, x
print(x)
print(y)

"""**Problem 13**

Assign the value 100 to three variables in a single statement.
"""

x = y = z = 100
print(x)
print(y)
print(z)

"""**Problem 14**

Assign the values 10, 20, and 30 to three variables in one line.
"""

x,y,z = 10,20,23
print(x,y,z)

"""**Problem 15**

Store an integer in a variable, then change it to a string and print its datatype before and after the change.
"""

x = 5 # int
print(type(x))

x = str(5)
print(type(x))

"""**Problem 16**

Create five variables using snake_case naming.
"""

# snake_case (Recommended in Python)
my_name = 'Anajli'
student_age = 23
house_price = 5500000
class_roll_no = 24003
team_1 = 'A'

"""**Problem 17**

Create three variables using camelCase naming.
"""

# camelCase (Valid, but not PEP 8)
myName = 'Anajli'
studentAge = 23
housePrice = 5500000

"""**Problem 18**

Create three variables using PascalCase naming.
"""

# PascalCase (Used for class names)
MyName = 'Anajli'
StudentAge = 23
HousePrice = 5500000

"""**Problem 19**

Create variables to store student information.Print all values.
"""

'''
student_info = {"name":"Anjali","age":23,"degree":"M.Sc"}
print(student_info) we can do this way too..
'''
student_name = "Anjali"
student_age = 23
student_degree = "M.Sc"

print(student_name)
print(student_age)
print(student_degree)

"""**Problem 20**

Create variables to store your favorite things.
"""

'''
favorite_things = {"language":"Python","editor":"VS Code","library":"Panads"}
print(favorite_things)
'''

language = "Python"
editor = "VS Code"
library = "Pandas"

print(language)
print(editor)
print(library)

"""**Data Types**

**Problem 21**

Create one variable of each Python data type.
"""

# Numeric data type
x = 5 # int
y = 2.3 # float
z = 3 + 4j # complex

# Text data type
name = "Anjali"

# Sequence data type
fruits = ["apple", "banana", 'cherry']
numbers = (1, 2, 3, 4, 3)

# Mapping data type
student_info = {
    "name":"Anjali",
    "age":24,
    "course":"M.Sc"
}

# Set data type
set_numbers = {1, 2, 3, 4}

# Boolean data type
is_active = True

# None data type
result = None

"""**Problem 22**

Print the datatype of every variable using type().
"""

# Numeric data type
x = 5
print(type(x))

y = 2.3
print(type(y))

z = 3 + 4j
print(type(z))

# Text data type
name = "Anjali"
print(type(name))

# Sequence data type
fruits = ["apple", "banana", 'cherry']
print(type(fruits))

numbers = (1, 2, 3, 4, 3)
print(type(numbers))

# Mapping data type
student_info = {
    "name":"Anjali",
    "age":24,
    "course":"M.Sc"
}
print(type(student_info))

# Set data type
set_numbers = {1, 2, 3, 4}
print(type(set_numbers))

# Boolean data type
is_active = True
print(type(is_active))

# None data type
result = None
print(type(result))
print(f"result = {result} --> {type(result)}")

"""**Problem 23**

Without running the code, predict the datatype of the following values.Then verify your answers using type().

10

10.5

"10"

True

None

[1, 2]

(1, 2)

{"a": 1}

{1, 2}

3 + 4j
"""

num = 10
print(f"num = {num} --> {type(num)}")

decimal = 10.5
print(f"decimal = {decimal} --> {type(decimal)}")

text = "10"
print(f"text = {text} --> {type(text)}")

is_student = True
print(f"is_student = {is_student} --> {type(is_student)}")

result = None
print(f"result = {result} --> {type(result)}")

numbers = [1, 2]
print(f"numbers = {numbers} --> {type(numbers)}")

cordinates = (1, 2)
print(f"cordinates = {cordinates} --> {type(cordinates)}")

info = {"a": 1}
print(f"info = {info} --> {type(info)}")

# we can also do this way too
unique_numbers = {1, 2}
print(f"{unique_numbers} --> {type(unique_numbers)}")

complex_num = 3 + 4j
print(f"{complex_num} --> {type(complex_num)}")

"""**Problem 24**

Create variables using constructor functions.
"""

num_int = int(5)
num_float = float(5)
text = str(5)
boolean = bool(5)
fruits_list = list(("apple", "banana"))
fruits_tuple = tuple(("apple", "banana"))
student = dict(name="Anjali", age=22)
numbers_set = set((1, 2, 3))

print(num_int)
print(num_float)
print(text)
print(boolean)
print(fruits_list)
print(fruits_tuple)
print(student)
print(numbers_set)

"""**Problem 25**

Create a student dictionary with:
Print the dictionary.
"""

student_dictionary = {
    "name":"Anjali",
    "age":24
}
print(student_dictionary)

"""**Problem 26**

Create a list of your five favorite programming tools.
"""

favorite_tools = ['VS Code', 'Pandas', 'Jupyter Notebook']
print(favorite_tools)

"""**Problem 27**

Create a tuple containing the names of all weekdays.
"""

weekdays_names = ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday' )
print(weekdays_names)

"""**Problem 28**

Create a set containing duplicate values and print the result.
"""

num_set = {1, 2, 3, 3, 4}
print(num_set) #A set stores only unique (distinct) values. It automatically removes duplicates.

"""**Problem 29**

Store different datatypes inside one list.
"""

list_of_dt = ["apple", 34, 5.6, 3+4j]
print(list_of_dt)
print(type(list_of_dt[0]))
print(type(list_of_dt[1]))
print(type(list_of_dt[2]))
print(type(list_of_dt[3]))

"""**Problem 30**

Create a complex number and print its datatype.
"""

number = 3+4j
print(type(number))

"""**Problem 31**

Print the datatype of:True
False
"""

is_student = True
has_job = False

print(type(is_student))
print(type(has_job))

"""**Problem 32**

Create a variable whose value is None and print its datatype.
"""

result = None
print(f"result = {result} --> {type(result)}")

"""**Problem 33**

Write a program that prints every variable along with its datatype.
"""

result = None
print(f"result = {type(result)}")

"""**Problem 34**

Show the difference between List and Tuple using code.
"""

list_numbers = [1, 2, 3, 4]
tuple_numbers = (1, 2, 3, 4)

list_numbers[2] = 10
#tuple_numbers[2] = 10 if we run this will raise a TypeError
print(list_numbers)
print(tuple_numbers)

"""**Problem 35**

Show the difference between Set and List using code.
"""

# List with duplicate values
numbers_list = [10, 20, 20, 30, 30, 40]

# Set with the same values
numbers_set = {10, 20, 20, 30, 30, 40}

print(numbers_list)
print(numbers_set)

"""**Numbers**

Problem 36 – Addition (+)
"""

num1 = 10
num2 = 15

sum_result = num1 + num2
print("sum =", sum_result)

"""Problem 37 – Subtraction (-)"""

num1 = 20
num2 = 12

difference = num1 - num2
print("Difference =", difference)

"""Problem 38 – Multiplication (*)"""

num1 = 6
num2 = 8

product = num1 * num2

print("Product =", product)

"""Problem 39 – Division (/)"""

num1 = 25
num2 = 5

quotient = num1 / num2

print("Quotient =", quotient)

"""Problem 40 – Floor Division (//)"""

num1 = 18
num2 = 4

result = num1 // num2

print("Result =", result)

"""Problem 41 – Modulus (%)"""

num1 = 20
num2 = 6

remainder = num1 % num2

print("Remainder =", remainder)

"""Problem 42 – Exponent (**)"""

base = 3
power = 4

result = base ** power

print("Result =", result)

"""Problem 43 – Convert Integer to Float"""

num = 4
num = float(4)
print(num)
print(type(num))

"""Problem 44 – Convert Float to Integer"""

num = 4.5
num = int(4)
print(num)
print(type(num))

"""Problem 45 – Scientific Notation"""

large_number = 1e5
small_number = 2e-3

print(large_number)
print(small_number)

"""Problem 46 – Complex Number"""

complex_number = 5 + 3j

print(complex_number)
print(type(complex_number))

"""Problem 47 – Find Remainder"""

number = 37
divisor = 5

remainder = number % divisor

print("Remainder =", remainder)

"""Problem 48 – Square of a Number"""

number = 12

square = number ** 2

print("Square =", square)

"""Problem 49 – Cube of a Number"""

number = 5

cube = number ** 3

print("Cube =", cube)

"""Problem 50 – Area of a Rectangle"""

length = 12
width = 5

area = length * width

print("Area =", area)

"""**Casting**

Problem 51: String to Integer
"""

'''
name = "Anjali"
name = int(name) not gone work ,The int() function can only convert strings that represent whole numbers.
'''
name = "23"
name = int(name)
print(name)

"""Problem 52: Integer to Float"""

num = 5
num = float(num)
print(num)

"""Problem 53: Float to String"""

num = 4.5
num = str(num)
print(num)
print(type(num))

"""Problem 54: Boolean to String"""

student_pass = True
student_pass = str(student_pass)
print(student_pass)
print(type(student_pass))

"""Problem 55: String to Float"""

num = 45.6
num = str(num)
print(num)
print(type(num))

"""Problem 56: Integer to Boolean"""

num = 34
num = bool(num)
print(num)

"""Problem 57: Float to Integer"""

num = 4.55
num = int(num)
print(num)

"""Problem 58: Multiple Casting"""

num_1 = 100
num_2 = 4.55
num_3 = "34"
print(f"num_1 = {num_1} --> {type(num_1)}")
print(f"num_2 = {num_2} --> {type(num_2)}")
print(f"num_3 = {num_3} --> {type(num_3)}")

"""Problem 59: Fix the Casting Error"""

'''
age = "23"
print(age + 5)
'''
age = "23"
age = int(age)
print(age + 5)

"""Problem 60: User Input (Integer)"""

age = int(input("Enter your age:"))
print("Next year you will be",age + 1)

"""Problem 61: User Input (Float)"""

salary = float(input("Enter your salary:"))
print(type(salary))

print(f"Salary: {salary}")
print(f"Datatype: {type(salary)}")

"""Problem 62: Two-Step Casting"""

#Convert the string "99.95" into an integer using two-step casting.
num = "99.95"
num = int(float(num))
print(num)

"""Problem 63: Datatype Before Casting"""

#Print the datatype of each variable before any conversion.
a = "150"
b = 75
c = 45.5
# Print datatypes before casting
print(type(a))
print(type(b))
print(type(c))

"""Problem 64: Datatype After Casting"""

a = "150"
b = 75
c = 45.5

# Casting
a = int(a)
b = float(b)
c = str(c)

# Print datatypes after casting
print(type(a))
print(type(b))
print(type(c))

"""Problem 65: Implicit vs Explicit Conversion"""

# Part A: Implicit Conversion

x = 10
y = 5.5

result = x + y

print("Part A: Implicit Conversion")
print("Result:", result)
print("Datatype:", type(result))

# Part B: Explicit Casting
y = int(y)   # Explicitly convert float to int

result = x + y

print("\nPart B: Explicit Casting")
print("Result:", result)
print("Datatype:", type(result))

"""**Input & Output**

Problem 66: Ask User's Name
"""

name = input("Enter your name:")
print(name)

"""Problem 67: Ask User's Age"""

age = int(input("Enter your age:"))
print("Your age is", age)

"""Problem 68: Ask User's City"""

city = input("Enter your city:")
print("You live in", city)

"""Problem 69: Print Multiple Values Using Commas

"""

name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")

print("Name:", name, "Age:", age, "City:", city, sep=",")

"""Problem 70: Print Using f-String

"""

name = input("Enter your name:")
age = int(input("Enter your age:"))
print(f"I am {name} and i am {age} year old")

"""Problem 71: Use sep Parameter"""

word_1 = input("Enter the word_1:")
word_2 = input("Enter the word_2:")
word_3 = input("Enter the word_3:")

print(f"i am leaing {word_1} for {word_2} {word_3}", sep="-")

"""Problem 72: Use end Parameter"""

word_1 = input("Enter the word_1:")
word_2 = input("Enter the word_2:")
word_3 = input("Enter the word_3:")

print(f"i am leaing {word_1} for {word_2} {word_3}", end="...")

"""Problem 73: Sum of Two Integers"""

#Write a Python program that asks the user to enter two integers and prints their sum.
num_1 = int(input("Enter first number:"))
num_2 = int(input("Enter second number:"))
sum = num_1 + num_2

print(f"Sum of 2 numbers:",sum)

"""Problem 74: Take Float Input"""

# Write a Python program that asks the user to enter a decimal number and prints its data type.
decimal_num = float(input("Enter a decimal number:"))
print(type(decimal_num))

"""Problem 75: Take Integer Input"""

# Write a Python program that asks the user to enter an integer and prints its data type.
int_num = int(input("Enter a int number:"))
print(type(int_num))

"""Problem 76: Next Year's Age"""

age = int(input("Enter your age:"))
print("Next year you will be",age + 1,"year old.")

"""Problem 77: Square of a Number"""

# Take input from the user
number = float(input("Enter a number: "))

# Calculate the square
square = number ** 2

# Display the result
print(f"Square = {square}")

"""Problem 78: Cube of a Number


"""

# Take input from the user
number = float(input("Enter a number: "))

# Calculate the square
square = number ** 3

# Display the result
print(f"Square = {square}")

"""Problem 79: Format Float to Two Decimal Places"""

# Take input from the user
number = float(input("Enter a decimal number: "))

# Display the formatted value
print(f"Formatted value = {number:.2f}")

"""Problem 80: Mini Student Information Program"""

# Take input from the user
name = input("Enter Name: ")
age = int(input("Enter Age: "))
city = input("Enter City: ")
course = input("Enter Course: ")
percentage = float(input("Enter Percentage: "))

# Display the information
print("\n------ Student Information ------\n")

print(f"Name       : {name}")
print(f"Age        : {age}")
print(f"City       : {city}")
print(f"Course     : {course}")
print(f"Percentage : {percentage:.2f}%")

"""**Global & Local Scopet**

Problem 81: Create Global Variable
"""

# Global variable
name = "Anjali"

# Access global variable
print(name)

"""Problem 82: Access Global Variable Inside Function"""

# Global variable
message = "Hello Python"


def display_message():
    print(message)


# Function call
display_message()

"""Problem 83: Create Local Variable"""

def student_info():
    # Local variable
    age = 23

    print(age)


student_info()

"""Problem 84: Access Local Variable Outside Function"""

def student_info():

    marks = 95   # Local variable

    print(marks)


student_info()

# print(marks) if you run this it rise error

"""Problem 85: Modify Global Variable Using global"""

# Global variable
count = 4


def update_count():

    global count

    count = count + 1


update_count()

print(count)

"""Problem 86: Create global variable inside function"""

def create_variable():
    global age
    age = 25


create_variable()

print(age)

"""Problem 87: Difference between local and global"""

name = "Anjali"   # Global variable


def student():
    age = 23      # Local variable
    print(name)
    print(age)


student()

print(name)

"""Problem 88: Print global variable before and after function call"""

count = 10


def update_count():
    global count
    count = 20


print(count)

update_count()

print(count)

"""Problem 89: Create two local variables"""

def student_info():
    name = "Anjali"
    age = 23

    print(name)
    print(age)


student_info()

"""Problem 90: Predict output"""

x = 50


def test():
    x = 20
    print(x)


test()

print(x)

"""**Comments & PEP8**

Problem 91: Write single-line comments
"""

# This program prints a message

print("Hello Python")

"""Problem 92: Write inline comments"""

age = 23  # Student age

print(age)

"""Problem 93: Write block comments"""

"""
This program calculates
the sum of two numbers.
"""

a = 10
b = 20

print(a + b)

"""Problem 94: Improve variable names"""

x = 25
y = "Anjali"

print(x, y)

student_age = 25
student_name = "Anjali"

print(student_age, student_name)

"""Problem 95: Fix spacing"""

a=10
b=20
print(a+b)

a = 10
b = 20

print(a + b)

"""Problem 96: Fix indentation"""

'''
if True:
print("Hello")
'''
if True:
    print("Hello")

"""Problem 97: Write PEP8-compliant code"""

student_name = "Anjali"
student_age = 23


def show_student():
    print(student_name)
    print(student_age)


show_student()

"""Problem 98: Separate logical sections"""

# Variables
name = "Anjali"
age = 23


# Calculation
birth_year = 2026 - age


# Output
print(name)
print(birth_year)

"""Problem 99: Add meaningful comments"""

# Store student's marks
marks = 85

# Check whether student passed
if marks >= 40:
    print("Pass")
else:
    print("Fail")

"""Problem 100: Clean and format messy Python program"""

name="Anjali"
age=23
if age>=18:
 print(name,"is adult")
else:
 print(name,"is child")



name = "Anjali"
age = 23


if age >= 18:
    print(name, "is adult")
else:
    print(name, "is child")